name: nobetcieczane
description: "."

publish_to: "none"

version: 2.0.2+11

environment:
  sdk: ^3.5.3

dependencies:
  connectivity_plus: ^7.0.0

  dio: ^5.7.0

  easy_localization: ^3.0.7

  envied: ^1.0.0
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1

  flutter_native_splash: ^2.4.1

  fpdart: ^1.1.1

  get_it: ^8.0.3

  google_maps_flutter: ^2.10.0

  google_mobile_ads: ^6.0.0

  internet_connection_checker_plus: ^2.9.0

  location: ^8.0.1

  shared_preferences: ^2.3.2

  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.14
  envied_generator: ^1.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  rename: ^3.0.2
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/translations/
    - assets/logo/
    - assets/map_styles/

flutter_native_splash:
  color: "#ff3232" # Arka plan rengini kırmızı yapar
  android_12:
    color: "#ff3232" # Android 12'de arka plan rengi
  ios: true # iOS desteği
  android: true # Android desteği
