name: nobetcieczane
description: "."

publish_to: "none"

version: 1.1.0+6

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  google_maps_flutter: ^2.9.0
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  location: ^6.0.2
  url_launcher: ^6.3.0
  google_mobile_ads: ^5.1.0
  flutter_native_splash: ^2.4.1
  easy_localization: ^3.0.7
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^3.0.2

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/translations/

flutter_native_splash:
  color: "ff3232"
  android_12:
    color: "#ff3232"
  color_android: "#ff3232"
