// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart
///
// ignore_for_file: lines_longer_than_80_chars, public_member_api_docs, constant_identifier_names

library;

///this file is automatically generated do not edit or manual changes
// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters,
// constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

/// Locale keys
class CodegenLoader extends AssetLoader {
  /// CodegenLoader
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  /// Map of locales
  static const Map<String, dynamic> en_US = {
    "app_name": "NÖBETÇİ ECZANE",
    "quick_search": "You can save districts for quick search",
    "snackbar_choose_city_district": "Please choose city and district",
    "snackbar_choose_city": "Please choose city",
    "search_text": "Search",
    "choose_city": "Choose City..",
    "choose_district": "Choose District..",
    "look_up_city_list": "Look up city list",
    "look_up_district_list": "Look up district list",
    "near_pharmacies_button_title": "Nearby Pharmacies",
    "near_pharmacies_button_subtitle": "View on duty pharmacies near you",
    "require_location_permission":
        "Location Permission Required, Please Allow Location Permission on Dialog Or From Settings",
    "confirm_pharmacy":
        "It is recommended that you call and confirm before going to pharmacies.",
    "no_duty_pharmacies": "There is no pharmacy on duty in this district.",
    "no_internet_connection": "No Internet Connection",
    "save_text": "Save",
    "delete_text": "Delete",
    "district_deleted": "District Deleted",
    "district_saved": "District Saved",
    "close_text": "Close",
    "map_view_app_bar": "Map",
    "loading": "Loading",
    "map_text": "Map",
    "list_text": "List",
    "settings_view_app_bar": "SETTINGS",
    "dark_theme": "Dark Theme",
    "language": "Language",
    "drawer_back": "BACK",
    "drawer_duty_pharmacies": "",
    "drawer_settings": "SETTINGS",
    "drawer_rate_us": "RATE US",
    "navigate_button": "Navigate Me",
    "null_pharmacy_name": "Pharmacy Name Not Found",
    "null_pharmacy_address": "Address Not Found",
    "null_pharmacy_phone": "Phone Number Not Found",
    "pharmacy_distance": "km away",
    "call_button": "Call",
  };
  static const Map<String, dynamic> tr_TR = {
    "app_name": "NÖBETÇİ ECZANE",
    "quick_search":
        "Daha hızlı arama yapabilmek için ilçeleri kaydedebilirsiniz",
    "snackbar_choose_city_district": "Lütfen şehir ve ilçe seçin",
    "snackbar_choose_city": "Lütfen önce şehir seçin",
    "search_text": "Ara",
    "choose_city": "Şehir Seçin..",
    "choose_district": "İlçe Seçin..",
    "look_up_city_list": "Şehir listesine göz atın",
    "look_up_district_list": "İlçe listesine göz atın",
    "near_pharmacies_button_title": "Yakınımdaki Eczaneler",
    "near_pharmacies_button_subtitle":
        "Yakınınızdaki nöbetçi eczaneleri görüntüleyin",
    "no_duty_pharmacies": "Bu ilçede nöbetçi eczane bulunmamaktadır",
    "require_location_permission":
        "Konum İzni Gerekli, Lütfen Dialog Ekranından veya Ayarlardan Konum İznini Kabul Edin",
    "save_text": "Kaydet",
    "no_internet_connection": "İnternet Bağlantısı Yok",
    "delete_text": "Sil",
    "district_deleted": "İlçe Silindi",
    "district_saved": "İlçe Kaydedildi",
    "close_text": "Kapat",
    "map_view_app_bar": "Harita",
    "loading": "Yükleniyor",
    "map_text": "Harita",
    "list_text": "Liste",
    "settings_view_app_bar": "AYARLAR",
    "dark_theme": "Karanlık Tema",
    "language": "Dil",
    "drawer_back": "GERİ",
    "drawer_duty_pharmacies": "NÖBETÇİ ECZANELER",
    "drawer_settings": "AYARLAR",
    "drawer_rate_us": "BİZİ DEĞERLENDİRİN",
    "navigate_button": "Yol Tarifi Al",
    "null_pharmacy_name": "İsim Bulunamadı",
    "null_pharmacy_address": "Adres Bulunamadı",
    "null_pharmacy_phone": "Telefon Numarası Bulunamadı",
    "pharmacy_distance": "km mesafede",
    "call_button": "Ara",
  };
  static const Map<String, Map<String, dynamic>> mapLocales = {
    "en_US": en_US,
    "tr_TR": tr_TR,
  };
}
